---
- name: Check connection
  hosts: comp2
  gather_facts: false
  tasks:
    - name: Получение имени компьютера
      ansible.windows.win_shell: hostname
      register: hostname_output

    - name: Вывод имени компьютера
      ansible.builtin.debug:
        msg: "Имя компьютера: {{ hostname_output.stdout }}"

    - name: WinPing
      ansible.windows.win_ping:
